### ISSUE TITLE
Build problems with "BuildOptimization" turned on

### ISSUE THREAD

**Issue by KyleW** [NetanelBasal/akita-ng-forms-manager#11]
I don't think this is an akitaNgFormsManager bug exactly, but I wanted to document it here in case there's a work around.

In Angular 6.1.10, ng-cli with "buildOptimization" set to true strips out calls to super in AkitaNgFormsManager. For details on the ng-cli bug see: https://github.com/shlomiassaf/angular-cli-build-optimizer-es2015-issue

The Angular team has fixed the issue here: angular/angular-cli#14263 But that doesn't help any of us on earlier versions of Angular.

I wonder if there's a possible fix on the library side?

**Comment by KyleW** [comment]
I don't think this is a akitaNgFormsManager bug exactly, but I wanted to document it here in case there's a work around.

In Angular 6.1.10, ng-cli with "buildOptimization" set to true strips out calls to super in AkitaNgFormsManager.  For details on the ng-cli bug see: https://github.com/shlomiassaf/angular-cli-build-optimizer-es2015-issue

The Angular team has fixed the issue here: https://github.com/angular/angular-cli/pull/14263 But that doesn't help any of us on earlier versions of Angular. 

I wonder if there's a possible fix on the library side?

**Comment by NetanelBasal** [comment]
Unfortunately, not.
