### ISSUE TITLE
Update peer dependency

### ISSUE THREAD

**Issue by Gustav0ar** [NetanelBasal/akita-ng-forms-manager#12]
Current akita version is 4.6.0, but ng-forms-manager still requires version 3.x as the following warning shows:
`warning " > @datorama/akita-ng-forms-manager@3.0.7" has incorrect peer dependency "@datorama/akita@^3.0.0".`

This project seems to work fine with the current Akita release...

**Comment by NetanelBasal** [comment]
Fixed in the latest version, thanks.
