### ISSUE TITLE
Array value in MultiSelect control

### ISSUE THREAD

**Issue by MetallIdea** [NetanelBasal/akita-ng-forms-manager#13]
If i have multiselect control on form, where value is array, FormsManager wants factory for FormArray.
Need to check. if existing control is FormArray (for example add check to condition on line 207):
https://github.com/NetanelBasal/akita-ng-forms-manager/blob/master/projects/datorama/akita-ng-forms-manager/src/lib/forms-manager.ts#L207
`        if (Array.isArray(value) && control.get(controlName) instanceof FormArray) {`

**Comment by NetanelBasal** [comment]
Can you show an example, please?

**Comment by MetallIdea** [comment]
as sample PrimeNg multiselect component https://www.primefaces.org/primeng/#/multiselect
`<p-multiSelect [options]="options" formControlName="MultiSelectValue" `[virtualScroll]="true"></p-multiSelect>`

`new FormGroup({
"MultiSelectValue": new FromControl([])
})`

FormGroup value:
`{
"MultiSelectValue": [1, 2, 3] // <--- Its a FormControl value, not FormArray
}`

**Comment by NetanelBasal** [comment]
Fixed in the latest version.
