### ISSUE TITLE
Most recent versions published on npm but missing from repo

### ISSUE THREAD

**Issue by KyleW** [NetanelBasal/akita-ng-forms-manager#14]
There's a mismatch between the various places versions are listed.

NPM shows:
<img width="765" alt="Screen Shot 2019-08-12 at 1 23 44 PM" src="https://user-images.githubusercontent.com/4153920/62895906-c25e7580-bd04-11e9-8bec-59c7fed0cf08.png">

But the release tab in github shows:
<img width="535" alt="Screen Shot 2019-08-12 at 1 25 36 PM" src="https://user-images.githubusercontent.com/4153920/62895895-bc689480-bd04-11e9-92a6-4ce10271a80d.png">

I'm trying to understand where those extra versions are coming from.

Maybe the releases weren't tagged correctly in git? Or some one is publishing to npm and not pushing back to the primary git repo?

**Comment by NetanelBasal** [comment]
The releases weren't tagged correctly in git. Thanks!
