### ISSUE TITLE
Version missing from package.json

### ISSUE THREAD

**Issue by KyleW** [NetanelBasal/akita-ng-forms-manager#15]
The package.json shows the version as "0.0.0" instead of whatever the actual version is.

I'm assuming version is being tracked in some other way (git tags? branches?), but it'd be nice to keep the package.json in sync so it's in the code as well.

**Comment by KyleW** [comment]
Slight revision. I see that there are actually 2 package.json files. One in root that doesn't a version and on in `akita-ng-forms-manager/projects/datorama/akita-ng-forms-manager/` that does. 

Should these be consolidated? As that the appropriate fix here?

**Comment by NetanelBasal** [comment]
There are the playground and the actual library. Here's the library version:
https://github.com/NetanelBasal/akita-ng-forms-manager/blob/master/projects/datorama/akita-ng-forms-manager/package.json#L4
