### ISSUE TITLE
Time Travel w/Redux DevTools

### ISSUE THREAD

**Issue by EigenTheory** [NetanelBasal/akita-ng-forms-manager#16]
Should Time Travel via Redux DevTools be able to replay state utilizing this plugin? I have tried both with my implementation and the demo for Akita-Filters and neither one seems to work. Just confirming if this is by design or a problem may be with DevTools etc.

**Comment by NetanelBasal** [comment]
Hi, it will not work. This plugin doesn't listen to store changes and updates the form.
