### ISSUE TITLE
Provide 'getRawValue()' method or 'rawValue' property for 'AkitaAbstractGroup'

### ISSUE THREAD

**Issue by ghost** [NetanelBasal/akita-ng-forms-manager#18]
Hi!

There is no raw value property for a form. When I try to do this `const form = this.formsManager.getForm('form').getRawValue()` or this `const form = this.formsManager.getForm('form').rawValue` I'm getting typescript lint error.

But I can do this `const form = this._formsManager.getForm('form')['rawValue']` because result object has rawValue property.

It would be great if you add this prop to AkitaAbstractGroup class.

Thanks!

**Comment by NetanelBasal** [comment]
Sure.

**Comment by NetanelBasal** [comment]
Fixed.
