### ISSUE TITLE
ERROR in node_modules/@datorama/akita-ng-forms-manager/lib/forms-manager.d.ts(24,73): error TS1005: '>' expected.

### ISSUE THREAD

**Issue by raihan71** [NetanelBasal/akita-ng-forms-manager#2]
I've installed akita ng form on angular 6

**Comment by NetanelBasal** [comment]
Can you reproduce it? (stackblitz or github)

**Comment by raihan71** [comment]
> Can you reproduce it? (stackblitz or github)

it's my private work

**Comment by raihan71** [comment]
I just followed the documentation

**Comment by NetanelBasal** [comment]
Which version you're installing?

**Comment by raihan71** [comment]
"@datorama/akita": "^1.24.2",
 "@datorama/akita-ng-forms-manager": "^1.0.0-rc.4",

**Comment by raihan71** [comment]
> Which version you're installing?

I need this plugin, it helps my work

**Comment by NetanelBasal** [comment]
Fixed in v1.0.0

**Comment by raihan71** [comment]
how to fixed

**Comment by NetanelBasal** [comment]
install v1.0.0

**Comment by raihan71** [comment]
> install v1.0.0

can you specify command should I run?

**Comment by NetanelBasal** [comment]
npm install @datorama/akita-ng-forms-manager

**Comment by raihan71** [comment]
> 
> 
> npm install @datorama/akita-ng-forms-manager

thanks so much

**Comment by raihan71** [comment]
npm install @datorama/akita-ng-forms-manager@1.0.0
