### ISSUE TITLE
Provide AbstractControl methods

### ISSUE THREAD

**Issue by ghost** [NetanelBasal/akita-ng-forms-manager#31]
Hi!

Is it possible to add methods like 'markAsDirty', 'markAsTouched' and other to plugin? It'll be very useful in many cases.

For example: I have a couple of forms on page. Each form located inside its own component. I need to mark all these form as touched when save button was clicked. How can I do that?

**Comment by NetanelBasal** [comment]
In the latest version, you can save the form instance, and access it in other components:

https://netbasal.gitbook.io/akita/angular/angular-forms-manager#persist-the-form-instance

**Comment by ghost** [comment]
I've missed that. Thanks a lot!
