### ISSUE TITLE
AkitaNgFormsManager not synced after page refresh

### ISSUE THREAD

**Issue by cojack** [NetanelBasal/akita-ng-forms-manager#32]
Hi,
I have a problem with `AkitaNgFormsManager` I do

```
  public ngOnInit(): void {
    this.formsManager.upsert('payment', this.paymentForm, { persistForm: true });
  }
```

state is in indexdb but form is empty, any advice? source code here: https://github.com/cojack/angular-akita-nestjs-socket.io/

at `web/src/app/examples/components/dirty-check/dirty-check.component.ts`

Do I miss something?

**Comment by NetanelBasal** [comment]
It's not persists after a page refresh. `persistForm` means it will persist the FormGroup instance so that you can use it in other components.

**Comment by cojack** [comment]
@NetanelBasal thanks for explanation, I will try `PersistNgFormPlugin` then.

Regards!
